### ISSUE TITLE
Encode types other than int

### ISSUE THREAD

**Issue by celluj34** [sqids/sqids-dotnet#14]
Hello;

I am looking to use your library to encode/decode an id/timestamp value. I need to use `GUID` for the ID and a `ulong` for the timestamp.

Is there any way to hash those values together, using this library?

**Comment by aradalvand** [comment]
Hi @celluj34.
The only other numeric type [we're considering adding support](https://github.com/sqids/sqids-dotnet/issues/10) for is `long`, I'm not sure if we'll add support `ulong`, etc.
Even the original [Hashids](https://github.com/ullmark/hashids.net) only supports `int` and `long`; you could see if Hashids fits your use case.

**Comment by aradalvand** [comment]
> I did see https://github.com/sqids/sqids-dotnet/pull/11; if generic math were implemented, would that make it easier to support other types like short, ulong, etc?

Yes, presumably.
Although I haven't personally looked into how exactly it would have to be implemented, but PRs are definitely welcome.

**Comment by celluj34** [comment]
Okay, sounds good! I'll see what that would take, maybe I can get a PR together. Thanks!
