### ISSUE TITLE
Is the Id still guessable even I have provided my own alphabet?

### ISSUE THREAD

**Issue by Rookian** [sqids/sqids-dotnet#19]
Is the Id still guessable even if have provided my own alphabet?
Is there a way to make the generated Id secure (e.g. using a salt)?

**Comment by aradalvand** [comment]
Hi @Rookian. Libraries like Sqids and Hashids are generally primarily used for aesthetic purposes, and even though they do also provide a decent level of obfuscation — meaning 99% of users won't be able to figure out the numbers behind your IDs — if someone is really determined, they can still technically decode your numbers.

Sqids/Hashids are not encryption algorithms (that would make them slow), if the stuff you're encoding with Sqids/Hashids are so sensitive that this is not acceptable in your scenario, then what you really need is a proper encryption algorithm.
