### ISSUE TITLE
A memory-alloc quesiton in the constructor of `SqidsEncoder`

### ISSUE THREAD

**Issue by LeaFrock** [sqids/sqids-dotnet#23]
Sorry to interrupt you again. I have a small question: why do you use `Span` in the following [codes](https://github.com/sqids/sqids-dotnet/blob/f40e66f2b4e88945eebcb4e849f154e365159df4/src/Sqids/SqidsEncoder.cs#L115C1-L121C42) ?

```csharp
                // TODO: `sizeof(T)` doesn't work, so we resorted to `sizeof(long)`, but ideally we should get it to work somehow — see https://github.com/sqids/sqids-dotnet/pull/15#issue-1872663234
		Span<char> shuffledAlphabet = options.Alphabet.Length * sizeof(long) > MaxStackallocSize // NOTE: We multiply the number of characters by the size of a `char` to get the actual amount of memory that would be allocated.
			? new char[options.Alphabet.Length]
			: stackalloc char[options.Alphabet.Length];
		options.Alphabet.AsSpan().CopyTo(shuffledAlphabet);
		ConsistentShuffle(shuffledAlphabet);
		_alphabet = shuffledAlphabet.ToArray();
```

First of all, the allocation of a char array for `_alphabet` is unavoidable.

Then, if the alphabet size is less than `MaxStackallocSize`, `shuffledAlphabet` is allocated on the stack but the last code line converts it to a `char[]`. Otherwise, `shuffledAlphabet.ToArray()` will create **another** new `char[]` and `shuffledAlphabet` is going to be collected by GC, which means double allocation.

Why not just let `shuffledAlphabet` be a char array and assign it to `_alphabet`? `Span` seems to be unnecessary here.

**Comment by aradalvand** [comment]
You're actually right! Great catch!
I'll make a PR to fix this!

**Comment by aradalvand** [comment]
Thank you @LeaFrock!
