### ISSUE TITLE
Ensure decoding an invalid ID with a repeating reserved character does not crash

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-dotnet#3]
Spec has been adjusted to include an additional check: https://github.com/sqids/sqids-spec/commit/f52b57836b0463097018f984f853b284e50a5ce4

What happens without that check is that when a reserved character (eg: offset character) is removed from the alphabet during decoding, conversion from ID to number becomes impossible when that same character is once again present in the ID (under normal conditions this never happens during encoding).

The best way to check for this is to try & decode an ID `fff` (like in the above link). Please ensure the library tests for that & returns an empty array under these conditions.

**Comment by aradalvand** [comment]
Sorry for the delay, I didn't notice this issue. I've enabled the "watch" feature from now to be notified when issues are created on this repo.

**Comment by aradalvand** [comment]
@4kimov I need to add a GitHub Actions secret to the repo but apparently I don't have the right permissions, this is the menu in the [settings page](https://github.com/sqids/sqids-dotnet/settings) for me:

![image](https://github.com/sqids/sqids-dotnet/assets/26527405/bb0d66b3-6b46-46f2-baa0-b0b887db5099)

This is what it should look like (this is from a repo I own):

![image](https://github.com/sqids/sqids-dotnet/assets/26527405/df525451-8dca-4cc8-9934-cc456c50c3ea)

Could you please modify my permissions to enable this?

**Comment by 4kimov** [comment]
@aradalvand Sure, done.
