### ISSUE TITLE
Sqids return same number if i change last character

### ISSUE THREAD

**Issue by vuanh1906** [sqids/sqids-dotnet#36]
I am using sqids for my application which returns Id with min length of 15 digits:

```
public static class IdHelper
{
    private static readonly SqidsEncoder<int> sqidsEncoder = new SqidsEncoder<int>(new()
    {
        MinLength = 15,
        Alphabet = "k3G7QAe51FCsPW92uEOyq4Bg6Sp8YzVTmnU0liwDdHXLajZrfxNhobJIRcMvKt",   
    });
    public static string Encode(int numericId)
    {
        return sqidsEncoder.Encode(numericId);
    }

    public static int Decode(string id)
    {
        return sqidsEncoder.Decode(id)[0];
    }
}
```

When I try to change a value of one character in the Encoded string, the int value returned is the same. I also tried changing the alphabet but still got the same error.
I use .NET 8, tried testing with the API and it appeared the above error, this error cannot be reproduced in the playground. 
Can someone help me clear this ? Did i made any mistake or misunderstanding?

**Comment by vuanh1906** [comment]
I use .NET Core, tried testing with the API and it appeared the above error, this error cannot be reproduced in the playground

**Comment by vuanh1906** [comment]
![image](https://github.com/sqids/sqids-dotnet/assets/100397231/bfd1d0b1-ff91-4dee-bb4b-0ee477079895)
![image](https://github.com/sqids/sqids-dotnet/assets/100397231/a19fe011-bac7-4f4d-81f0-d85d788c859d)
![image](https://github.com/sqids/sqids-dotnet/assets/100397231/ef2b4d7d-b0ce-44de-b332-b5f682ceda4e)

**Comment by BraedonWooding** [comment]
This is due to your max length.  You can do a canonicalisation check like in the readme; https://github.com/sqids/sqids-dotnet?tab=readme-ov-file#ensuring-an-id-is-canonical

**Comment by vuanh1906** [comment]
Thanks Braedon, I understand now
